version: '3.8'

services:
  postgres_database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: interact
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis_cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass "redis"
volumes:
  db_data:
  redis_data:
