version: '3.8'

services:
  postgres_database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: interact
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
